CREATE TABLE tb_usuario
(
    usuario_id    UUID         NOT NULL,
    cpf_usuario   VARCHAR(11)  NOT NULL,
    nome_usuario  VARCHAR(255) NOT NULL,
    email_usuario VARCHAR(255),
    senha_usuario VARCHAR(255) NOT NULL,
    CONSTRAINT pk_tb_usuario PRIMARY KEY (usuario_id)
);

CREATE TABLE tb_usuario_roles
(
    usuario_id UUID NOT NULL,
    role_user  VARCHAR(255)
);

ALTER TABLE tb_usuario
    ADD CONSTRAINT uc_tb_usuario_cpf_usuario UNIQUE (cpf_usuario);

ALTER TABLE tb_usuario
    ADD CONSTRAINT uc_tb_usuario_email_usuario UNIQUE (email_usuario);

ALTER TABLE tb_usuario_roles
    ADD CONSTRAINT fk_tb_usuario_roles_on_usuario_entity FOREIGN KEY (usuario_id) REFERENCES tb_usuario (usuario_id);



CREATE TABLE tb_professor
(
    professor_id UUID NOT NULL,
    usuario_id   UUID NOT NULL,
    CONSTRAINT pk_tb_professor PRIMARY KEY (professor_id)
);

ALTER TABLE tb_professor
    ADD CONSTRAINT uc_tb_professor_usuario UNIQUE (usuario_id);

ALTER TABLE tb_professor
    ADD CONSTRAINT FK_TB_PROFESSOR_ON_USUARIO FOREIGN KEY (usuario_id) REFERENCES tb_usuario (usuario_id);



CREATE TABLE tb_aluno
(
    aluno_id       UUID NOT NULL,
    data_matricula TIMESTAMP WITHOUT TIME ZONE,
    usuario_id     UUID NOT NULL,
    CONSTRAINT pk_tb_aluno PRIMARY KEY (aluno_id)
);

ALTER TABLE tb_aluno
    ADD CONSTRAINT uc_tb_aluno_usuario UNIQUE (usuario_id);

ALTER TABLE tb_aluno
    ADD CONSTRAINT FK_TB_ALUNO_ON_USUARIO FOREIGN KEY (usuario_id) REFERENCES tb_usuario (usuario_id);



CREATE TABLE tb_aula
(
    aula_id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    professor_id        UUID NOT NULL,
    titulo_aula         VARCHAR(255)                            NOT NULL,
    data_hora           TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    capacidade_max_aula INTEGER NOT NULL,
    CONSTRAINT pk_tb_aula PRIMARY KEY (aula_id)
);

ALTER TABLE tb_aula
    ADD CONSTRAINT FK_TB_AULA_ON_PROFESSOR FOREIGN KEY (professor_id) REFERENCES tb_professor (professor_id);



CREATE SEQUENCE IF NOT EXISTS tb_agendamento_seq START WITH 1 INCREMENT BY 50;

CREATE TABLE tb_agendamento
(
    agendamento_id BIGINT NOT NULL,
    aula_id        BIGINT NOT NULL,
    aluno_id       UUID   NOT NULL,
    CONSTRAINT pk_tb_agendamento PRIMARY KEY (agendamento_id)
);

ALTER TABLE tb_agendamento
    ADD CONSTRAINT FK_TB_AGENDAMENTO_ON_ALUNO FOREIGN KEY (aluno_id) REFERENCES tb_aluno (aluno_id);

ALTER TABLE tb_agendamento
    ADD CONSTRAINT FK_TB_AGENDAMENTO_ON_AULA FOREIGN KEY (aula_id) REFERENCES tb_aula (aula_id);